// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import lint "github.com/jgeewax/api-linter/lint"
import mock "github.com/stretchr/testify/mock"
import protoreflect "github.com/golang/protobuf/v2/reflect/protoreflect"

// Request is an autogenerated mock type for the Request type
type Request struct {
	mock.Mock
}

// Context provides a mock function with given fields:
func (_m *Request) Context() lint.Context {
	ret := _m.Called()

	var r0 lint.Context
	if rf, ok := ret.Get(0).(func() lint.Context); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(lint.Context)
	}

	return r0
}

// ProtoFile provides a mock function with given fields:
func (_m *Request) ProtoFile() protoreflect.FileDescriptor {
	ret := _m.Called()

	var r0 protoreflect.FileDescriptor
	if rf, ok := ret.Get(0).(func() protoreflect.FileDescriptor); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(protoreflect.FileDescriptor)
		}
	}

	return r0
}
