// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import lint "github.com/jgeewax/api-linter/lint"
import mock "github.com/stretchr/testify/mock"

// Rule is an autogenerated mock type for the Rule type
type Rule struct {
	mock.Mock
}

// Info provides a mock function with given fields:
func (_m *Rule) Info() lint.RuleInfo {
	ret := _m.Called()

	var r0 lint.RuleInfo
	if rf, ok := ret.Get(0).(func() lint.RuleInfo); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(lint.RuleInfo)
	}

	return r0
}

// Lint provides a mock function with given fields: _a0
func (_m *Rule) Lint(_a0 lint.Request) (lint.Response, error) {
	ret := _m.Called(_a0)

	var r0 lint.Response
	if rf, ok := ret.Get(0).(func(lint.Request) lint.Response); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(lint.Response)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(lint.Request) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
