// Code generated by `go run gen/gen_imports.go && go fmt`. DO NOT EDIT.
package protos

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"    //"google/api/resource.proto"
	_ "google.golang.org/genproto/googleapis/api/configchange"   //"google/api/config_change.proto"
	_ "google.golang.org/genproto/googleapis/api/distribution"   //"google/api/distribution.proto"
	_ "google.golang.org/genproto/googleapis/api/httpbody"       //"google/api/httpbody.proto"
	_ "google.golang.org/genproto/googleapis/api/label"          //"google/api/label.proto"
	_ "google.golang.org/genproto/googleapis/api/metric"         //"google/api/metric.proto"
	_ "google.golang.org/genproto/googleapis/api/monitoredres"   //"google/api/monitored_resource.proto"
	_ "google.golang.org/genproto/googleapis/api/serviceconfig"  //"google/api/usage.proto"
	_ "google.golang.org/genproto/googleapis/iam/admin/v1"       //"google/iam/admin/v1/iam.proto"
	_ "google.golang.org/genproto/googleapis/iam/v1"             //"google/iam/v1/policy.proto"
	_ "google.golang.org/genproto/googleapis/iam/v1/logging"     //"google/iam/v1/logging/audit_data.proto"
	_ "google.golang.org/genproto/googleapis/logging/type"       //"google/logging/type/log_severity.proto"
	_ "google.golang.org/genproto/googleapis/longrunning"        //"google/longrunning/operations.proto"
	_ "google.golang.org/genproto/googleapis/rpc/code"           //"google/rpc/code.proto"
	_ "google.golang.org/genproto/googleapis/rpc/errdetails"     //"google/rpc/error_details.proto"
	_ "google.golang.org/genproto/googleapis/rpc/status"         //"google/rpc/status.proto"
	_ "google.golang.org/genproto/googleapis/type/color"         //"google/type/color.proto"
	_ "google.golang.org/genproto/googleapis/type/date"          //"google/type/date.proto"
	_ "google.golang.org/genproto/googleapis/type/dayofweek"     //"google/type/dayofweek.proto"
	_ "google.golang.org/genproto/googleapis/type/latlng"        //"google/type/latlng.proto"
	_ "google.golang.org/genproto/googleapis/type/money"         //"google/type/money.proto"
	_ "google.golang.org/genproto/googleapis/type/postaladdress" //"google/type/postal_address.proto"
	_ "google.golang.org/genproto/googleapis/type/timeofday"     //"google/type/timeofday.proto"
)
