// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import protoreflect "github.com/golang/protobuf/v2/reflect/protoreflect"

// DescriptorVisiting is an autogenerated mock type for the DescriptorVisiting type
type DescriptorVisiting struct {
	mock.Mock
}

// VisitDescriptor provides a mock function with given fields: _a0
func (_m *DescriptorVisiting) VisitDescriptor(_a0 protoreflect.Descriptor) {
	_m.Called(_a0)
}
