// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import protoreflect "github.com/golang/protobuf/v2/reflect/protoreflect"

// DescriptorVisitor is an autogenerated mock type for the DescriptorVisitor type
type DescriptorVisitor struct {
	mock.Mock
}

// PostVisit provides a mock function with given fields: _a0
func (_m *DescriptorVisitor) PostVisit(_a0 protoreflect.Descriptor) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(protoreflect.Descriptor) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PreVisit provides a mock function with given fields: _a0
func (_m *DescriptorVisitor) PreVisit(_a0 protoreflect.Descriptor) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(protoreflect.Descriptor) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
