// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import protoreflect "github.com/golang/protobuf/v2/reflect/protoreflect"

// EnumVisiting is an autogenerated mock type for the EnumVisiting type
type EnumVisiting struct {
	mock.Mock
}

// VisitEnum provides a mock function with given fields: _a0
func (_m *EnumVisiting) VisitEnum(_a0 protoreflect.EnumDescriptor) {
	_m.Called(_a0)
}

// VisitEnumValue provides a mock function with given fields: _a0
func (_m *EnumVisiting) VisitEnumValue(_a0 protoreflect.EnumValueDescriptor) {
	_m.Called(_a0)
}
