// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import protoreflect "github.com/golang/protobuf/v2/reflect/protoreflect"

// ExtensionVisiting is an autogenerated mock type for the ExtensionVisiting type
type ExtensionVisiting struct {
	mock.Mock
}

// VisitExtension provides a mock function with given fields: _a0
func (_m *ExtensionVisiting) VisitExtension(_a0 protoreflect.FieldDescriptor) {
	_m.Called(_a0)
}
