// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import protoreflect "github.com/golang/protobuf/v2/reflect/protoreflect"

// MessageVisiting is an autogenerated mock type for the MessageVisiting type
type MessageVisiting struct {
	mock.Mock
}

// VisitEnum provides a mock function with given fields: _a0
func (_m *MessageVisiting) VisitEnum(_a0 protoreflect.EnumDescriptor) {
	_m.Called(_a0)
}

// VisitEnumValue provides a mock function with given fields: _a0
func (_m *MessageVisiting) VisitEnumValue(_a0 protoreflect.EnumValueDescriptor) {
	_m.Called(_a0)
}

// VisitExtension provides a mock function with given fields: _a0
func (_m *MessageVisiting) VisitExtension(_a0 protoreflect.FieldDescriptor) {
	_m.Called(_a0)
}

// VisitField provides a mock function with given fields: _a0
func (_m *MessageVisiting) VisitField(_a0 protoreflect.FieldDescriptor) {
	_m.Called(_a0)
}

// VisitMessage provides a mock function with given fields: _a0
func (_m *MessageVisiting) VisitMessage(_a0 protoreflect.MessageDescriptor) {
	_m.Called(_a0)
}

// VisitOneof provides a mock function with given fields: _a0
func (_m *MessageVisiting) VisitOneof(_a0 protoreflect.OneofDescriptor) {
	_m.Called(_a0)
}
