// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import protoreflect "github.com/golang/protobuf/v2/reflect/protoreflect"

// ServiceVisiting is an autogenerated mock type for the ServiceVisiting type
type ServiceVisiting struct {
	mock.Mock
}

// VisitMethod provides a mock function with given fields: _a0
func (_m *ServiceVisiting) VisitMethod(_a0 protoreflect.MethodDescriptor) {
	_m.Called(_a0)
}

// VisitService provides a mock function with given fields: _a0
func (_m *ServiceVisiting) VisitService(_a0 protoreflect.ServiceDescriptor) {
	_m.Called(_a0)
}
