---
name: Unit tests
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    container: golang:1.14
    steps:
      - uses: actions/checkout@v2
      - run: go test -p 1 ./...
